### ISSUE TITLE
grey points in auto-scale should not be medians but instead minima

### ISSUE THREAD

**Issue by seanastephens** [hdc-arizona/synteny-vis#14]
Talked about on 8/26: By choosing minumums, we unfairly grey out some points. Median appears to be a better heuristic for now.

**Comment by seanastephens** [comment]
At some point it was decided that coloring the valleys was better.

**Comment by cscheid** [comment]
Just for sake of completeness of information; the request to color valleys came from Eric during our last meeting.

-carlos
