### ISSUE TITLE
Whole visualization should render into a div so we can integrate into results page.

### ISSUE THREAD

**Issue by asherkhb** [hdc-arizona/synteny-vis#20]
![div-issue](https://cloud.githubusercontent.com/assets/8932833/15834455/753a7d84-2be0-11e6-85d5-3961adab0495.png)

**Comment by seanastephens** [comment]
This should be fixed in d651386a3224aca8a33e5046baa9bd8e77f57473

@asherkhb let me know if it looks better on your end.

**Comment by asherkhb** [comment]
Looks like that is working for us now, thanks.
