### ISSUE TITLE
Color scheme error

### ISSUE THREAD

**Issue by asherkhb** [hdc-arizona/synteny-vis#23]
It appears that the color scheme doesn't always translate between the brushing the histogram and plot. I have noticed particulaly just left of center on the histogram shows up the same color as just right of histogram.

![screenshot 2016-07-14 11 07 28](https://cloud.githubusercontent.com/assets/8932833/16850274/33dd8124-49b3-11e6-887c-ec7939790526.png)

![screenshot 2016-07-14 11 00 31](https://cloud.githubusercontent.com/assets/8932833/16850240/11213450-49b3-11e6-8db5-a2be7a126bff.png)

**Comment by asherkhb** [comment]
this appears to be pretty inconsistent, not sure what is causing it...might just be a D3 fluke

**Comment by seanastephens** [comment]
This got fixed in 62d11a2, as far as I can tell -- I wasn't able to reproduce the above scenario.
