### ISSUE TITLE
points without ks data should render into a dotplot but without histogram

### ISSUE THREAD

**Issue by asherkhb** [hdc-arizona/synteny-vis#24]
These files are presented as "\*.gcoords" rather than "\*.gcoords.ks". They have two less columns

i.e. 
* Current files, with Ks
https://geco.iplantcollaborative.org/asherkhb/coge/data/diags/6807/8082/6807_8082.CDS-CDS.last.tdd10.cs0.filtered.dag.all.go_D20_g10_A5.aligncoords.qac1.2.40.gcoords.ks
* File without Ks
https://geco.iplantcollaborative.org/asherkhb/coge/data/diags/6807/8082/6807_8082.CDS-CDS.last.tdd10.cs0.filtered.dag.all.go_D20_g10_A5.aligncoords.qac1.2.40.gcoords

**Comment by seanastephens** [comment]
I must be missing something in the test cases I have tried. I am not sure how to find a genome pair without ks data -- could you provide a link to a dotplot without ks or a description of how to generate that?

**Comment by asherkhb** [comment]
Here is an analysis between Corn & Sorghum, both with Ks (first) and without (second). Basically, there are two additional columns at the beginning when Kn Ks calculations are made. Also, filenames differ: *.gcoords.ks (with Kn Ks) and *.gcoords (*no* Kn Ks).

If you want to see how it looks currently, check out the "test" tab. As I'm writing this, it is only up to date on the "dev" links, but this could change. You will notice if you try with the link without Kn Ks calculations, the "test" plot is blank.

* Corn vs Sorghum, with Kn & Ks Calculations
** Regenerate Analysis (dev): https://genomevolution.org/r/l2a3
** Regenerate Analysis (production): https://genomevolution.org/r/k7t4
** Resulting Data File: https://geco.iplantcollaborative.org/asherkhb/coge/data/diags/6807/8082/6807_8082.CDS-CDS.last.tdd10.cs0.filtered.dag.all.go_D20_g10_A5.aligncoords.qac1.2.40.gcoords.ks
* Corn vs Sorghum, *WITHOUT* Kn & Ks Calculations
** Regenerate Analysis (dev): https://genomevolution.org/r/l2a1
** Regenerate Analysis (production): https://genomevolution.org/r/k7sv
** Data File: https://geco.iplantcollaborative.org/asherkhb/coge/data/diags/6807/8082/6807_8082.CDS-CDS.last.tdd10.cs0.filtered.dag.all.go_D20_g10_A5.aligncoords.qac1.2.40.gcoords

**Comment by seanastephens** [comment]
The link that gets passed in is

    https://geco.iplantcollaborative.org/home/asherkhb/repos/coge/web/data/diags//6807/8082/6807_8082.CDS-CDS.last.tdd10.cs0.filtered.dag.all.go_D20_g10_A5.aligncoords.gcoords

which differs from your data file link (/home/asherkb/repos/coge v. /asherkb/coge). It goes to a 404. Is this something you can take a look at?

**Comment by asherkhb** [comment]
Oops sorry, fixed!

**Comment by seanastephens** [comment]
This looks fixed. I can look at making the dotplot take up more of the screen, etc. after #25
