### ISSUE TITLE
resizing doesn't behave correctly

### ISSUE THREAD

**Issue by asherkhb** [hdc-arizona/synteny-vis#25]
Visualizations don't update correctly when pages are resized.
![screenshot 2016-07-26 14 15 33](https://cloud.githubusercontent.com/assets/8932833/17155823/9d995b24-533b-11e6-83df-6828bb7173d4.png)
![screenshot 2016-07-26 14 16 13](https://cloud.githubusercontent.com/assets/8932833/17155827/9f6b0e0c-533b-11e6-991d-20259bfd9cd9.png)

**Comment by asherkhb** [comment]
It'd be really nice to be able to resize the visualization also. This may be possible my simply constraining the size of the parent div? In which case, we can handle but this would probably require vis to update correctly on resize still

**Comment by seanastephens** [comment]
This is done.
