### ISSUE TITLE
Labels can overlap

### ISSUE THREAD

**Issue by asherkhb** [hdc-arizona/synteny-vis#26]
![screenshot 2016-07-26 14 27 44](https://cloud.githubusercontent.com/assets/8932833/17156148/205fa4fe-533d-11e6-937a-25f8202e6994.png)

**Comment by seanastephens** [comment]
Hm, not sure the best way to fix this. I'll look at ways of re-organizing the labels, but a better approach might be to abbreviate the labels or only show them on mouse over.

**Comment by seanastephens** [comment]
Fixed in c24d643b.
