### ISSUE TITLE
reorder chromosomes by size or name

### ISSUE THREAD

**Issue by asherkhb** [hdc-arizona/synteny-vis#35]
Option can go into "Controls" section

**Comment by asherkhb** [comment]
can we move this one up in priority? it's a popular option!

**Comment by seanastephens** [comment]
Noted. I can take a look this weekend. Out of curiosity, are you getting feedback or is this based on the static version?

**Comment by cscheid** [comment]
Fixed by a660caae0a2cc8c33d04a3d864cb55490011792f. @asherkhb, take a look at this. Lexicographical sorting is not quite the right thing, ("10" < "2", for example). But it should be a start. We'll probably need more metadata to do name sorting correctly.

**Comment by asherkhb** [comment]
In the 3D version I used a Python module called "natsorted" (http://natsort.readthedocs.io/en/stable/intro.html). Perhaps there is a similar thing that could be used here?

**Comment by cscheid** [comment]
Cute. This is probably the equivalent. https://www.npmjs.com/package/javascript-natural-sort It should be easy for me to incorporate. I'll set aside some time on Friday.

**Comment by cscheid** [comment]
Yeah, I think this looks right:

![image](https://user-images.githubusercontent.com/285675/27043378-cdc2c942-4f4e-11e7-9a14-c144498fca10.png)
