### ISSUE TITLE
Kn/Ks coloring is acting wrong

### ISSUE THREAD

**Issue by asherkhb** [hdc-arizona/synteny-vis#36]
Kn/Ks histogram & dotplot colors don't seem to be mapping correct
![screenshot 2016-08-31 13 31 12](https://cloud.githubusercontent.com/assets/8932833/18145273/56119428-6f7f-11e6-9261-5a3a44790281.png)
![screenshot 2016-08-31 13 31 17](https://cloud.githubusercontent.com/assets/8932833/18145276/5969daa4-6f7f-11e6-8dfc-586d3d59ae0e.png)

**Comment by seanastephens** [comment]
![image](https://cloud.githubusercontent.com/assets/5893305/18155067/9b8e0826-6fbe-11e6-865a-e540ba70d8e9.png)

Should be fixed.
