### ISSUE TITLE
Labels collide with species name

### ISSUE THREAD

**Issue by seanastephens** [hdc-arizona/synteny-vis#43]
Currently, if chromosome labels are long they will extend into the name of the species on the y-axis. On the x-axis we don't have this problem, but names extend into each other.

Asher proposed a three part solution:

* Cut off names at a maximum length
* Angle the names at 45 degrees to better utilize the space
* Potentially shrink the plot to accommodate the longer labels

**Comment by asherkhb** [comment]
Any idea on how long this might take to implement? We have a deadline for resubmission on the 22nd and it'd be good to have in a few days early for testing!

**Comment by seanastephens** [comment]
@asherkhb Let me know what you think: http://hdc-arizona.github.io/synteny-vis/#h

Long labels are truncated, but you can mouse over them to see the full names. I haven't added angled labels yet, because it seemed cluttered. Happy to do so if you think it helps.

**Comment by asherkhb** [comment]
that looks fantastic! I agree there is no need to angle the labels now. Thanks!

**Comment by asherkhb** [comment]
Can we apply that same hide/cut-off to ones that would overlap on the X axis too?

**Comment by seanastephens** [comment]
It is already done. Here is one of the few examples I have for which you can see it: http://hdc-arizona.github.io/synteny-vis/#z. I'm noticing now that the threshold I use for which labels to provide is too small (there are two overlapped labels at the bottom right: "7" and "Sc.."):

![image](https://cloud.githubusercontent.com/assets/5893305/21233808/da6d05e6-c2ad-11e6-84ab-3a23bd93af06.png)

I'll fix that now.

Unfortunately, expanding names on the x-axis isn't very nice because they tend to overlap with adjacent names. The right thing to do here might be to hide adjacent names if they would be covered up by an expanded name, but not totally sure.

**Comment by asherkhb** [comment]
hiding adjacent on hover sounds like a good idea - or if a hover one overlaps it could get lowered a bit to show up under the other ones?

**Comment by seanastephens** [comment]
See what you think of http://hdc-arizona.github.io/synteny-vis/#h. I've artifically lengthened the chromosome names to highlight the interaction we are working on.

**Comment by seanastephens** [comment]
One thing I just noticed was that as we zoom in, we could potentially avoid shortening label names and just display the whole name, because the chromosomes take up a large fraction of the screen. On the other hand, that only works on the x-axis, so not sure if that's worth it.

**Comment by asherkhb** [comment]
Looks really good! If the not shortening on zoom for x axis is easy to do, it'd be neat, but I don't think it's absolutely necessary.

**Comment by seanastephens** [comment]
I'll merge this in and re-visit that in the future.
